namespace ResourceEnum
{
    public enum Prefab
    {
        Test,
        Survivor,
        Bullet,
        Rocket,
        Beam,
        Blood,
        BearTrap,
        LandMine,

        // Effects
        Explosion,
        GasLeak,

        // Map
        Map_2x2_01,
        Map_2x2_02,
        Map_2x2_03,
        Map_2x2_04,
        Map_2x2_05,
        Map_2x2_06,
        Map_2x2_07,
        Map_2x2_08,
        Map_2x2_09,
        Map_2x2_10,
        Map_3x3_01,
        Map_3x3_02,
        Map_3x3_03,
        Map_3x3_04,
        Map_3x3_05,
        Map_4x4_01,
        Map_4x4_02,
        Map_5x5_01,

        // UI
        Alert,
        SurvivorSchedule,
        CraftableAllow,
        ImageBox,

        // In Game UI
        KillLog,
        Headshot,
    }

    public enum NavMeshData
    {
        Map_2x2_01,
        Map_2x2_02,
        Map_2x2_03,
        Map_2x2_04,
        Map_2x2_05,
        Map_2x2_06,
        Map_2x2_07,
        Map_2x2_08,
        Map_2x2_09,
        Map_2x2_10,
        Map_3x3_01,
        Map_3x3_02,
        Map_3x3_03,
        Map_3x3_04,
        Map_3x3_05,
        Map_4x4_01,
        Map_4x4_02,
        Map_5x5_01,
    }

    public enum Sprite
    {
        Survivor,
        Box,
        // Melee Weapons
        Knife,
        Dagger,
        Bat,
        LongSword,
        Shovel,
        // RangedWeapon
        Revolver,
        Pistol,
        AssaultRifle,
        SubMachineGun,
        ShotGun,
        SniperRifle,
        Bazooka,
        LASER,
        // Bullets
        Bullet_Revolver,
        Bullet_Pistol,
        Bullet_AssaultRifle,
        Bullet_SubMachineGun,
        Bullet_ShotGun,
        Bullet_SniperRifle,
        Rocket_Bazooka,
        // BulletproofHats
        LowLevelBulletproofHelmet,
        MiddleLevelBulletproofHelmet,
        HighLevelBulletproofHelmet,
        LegendaryBulletproofHelmet,
        // BulletproofVests
        LowLevelBulletproofVest,
        MiddleLevelBulletproofVest,
        HighLevelBulletproofVest,
        LegendaryBulletproofVest,
        // Consumables
        BandageRoll,
        HemostaticBandageRoll,
        Poison,
        Antidote,
        Potion,
        AdvancedPotion,
        // Traps
        BearTrap,
        LandMine,
        NoiseTrap,
        ChemicalTrap,
        ShrapnelTrap,
        ExplosiveTrap,
        // Crafting Materials
        AdvancedComponent,
        Components,
        Chemicals,
        Salvages,
        Gunpowder,
        // ETC
        WalkingAid,
        TrapDetectionDevice,
        BiometricRader,
        EnergyBarrier,

        // Leagues
        BronzeLeague,
        SilverLeague,
        GoldLeague,
        SeasonChampionship,
        WorldChampionship,
        MeleeLeague,
        RangeLeague,
        CraftingLeague,
        
        BronzeLeagueKR,
        BronzeLeagueJP,
        BronzeLeagueTC,
        BronzeLeagueSC,
        BronzeLeagueFR,
        BronzeLeagueDE,
        BronzeLeagueRU,
        BronzeLeagueES,
        BronzeLeaguePT,
        SilverLeagueKR,
        SilverLeagueJP,
        SilverLeagueTC,
        SilverLeagueSC,
        SilverLeagueFR,
        SilverLeagueDE,
        SilverLeagueRU,
        SilverLeagueES,
        SilverLeaguePT,
        GoldLeagueKR,
        GoldLeagueJP,
        GoldLeagueTC,
        GoldLeagueSC,
        GoldLeagueFR,
        GoldLeagueDE,
        GoldLeagueRU,
        GoldLeagueES,
        GoldLeaguePT,
        SeasonChampionshipKR,
        SeasonChampionshipJP,
        SeasonChampionshipTC,
        SeasonChampionshipSC,
        SeasonChampionshipFR,
        SeasonChampionshipDE,
        SeasonChampionshipRU,
        SeasonChampionshipES,
        SeasonChampionshipPT,
        WorldChampionshipKR,
        WorldChampionshipJP,
        WorldChampionshipTC,
        WorldChampionshipSC,
        WorldChampionshipFR,
        WorldChampionshipDE,
        WorldChampionshipRU,
        WorldChampionshipES,
        WorldChampionshipPT,
        MeleeLeagueKR,
        MeleeLeagueJP,
        MeleeLeagueTC,
        MeleeLeagueSC,
        MeleeLeagueFR,
        MeleeLeagueDE,
        MeleeLeagueRU,
        MeleeLeagueES,
        MeleeLeaguePT,
        RangeLeagueKR,
        RangeLeagueJP,
        RangeLeagueTC,
        RangeLeagueSC,
        RangeLeagueFR,
        RangeLeagueDE,
        RangeLeagueRU,
        RangeLeagueES,
        RangeLeaguePT,
        CraftingLeagueKR,
        CraftingLeagueJP,
        CraftingLeagueTC,
        CraftingLeagueSC,
        CraftingLeagueFR,
        CraftingLeagueDE,
        CraftingLeagueRU,
        CraftingLeagueES,
        CraftingLeaguePT,

        // Tiers
        Bronze,
        Silver,
        Gold,

        // Minimaps
        Minimap_2x2_01,
        Minimap_2x2_02,
        Minimap_2x2_03,
        Minimap_2x2_04,
        Minimap_2x2_05,
        Minimap_2x2_06,
        Minimap_2x2_07,
        Minimap_2x2_08,
        Minimap_2x2_09,
        Minimap_2x2_10,
        Minimap_3x3_01,
        Minimap_3x3_02,
        Minimap_3x3_03,
        Minimap_3x3_04,
        Minimap_3x3_05,
        Minimap_4x4_01,
        Minimap_4x4_02,
        Minimap_5x5_01,

    }

    public enum Material
    {
        Sight_Normal,
        Sight_Suspicious,
        Sight_Alert,
    }

    public enum BGM
    {
        the_birth_of_hip_hop,
    }

    public enum SFX
    {
        assaultriflereload1,
        Handgun_reload,
        revolver_reload,
        Shotgun_singlebullet,
        Rack,
        metal_hit,
        bang_01, // Revolver
        bang_02, // Pistol
        bang_03, // Submuchinegun
        bang_04, // Shotgun
        bang_05, // Sniper riple
        bang_06, // Assult riple
        rocket_launch,
        laser,
        ricochet,
        ricochet2,
        hit01,
        hit02,
        hit_flesh,
        guard,
        avoid,
        farmingNoise01,
        farmingNoise02,
        farmingNoise03,
        farmingNoise04,
        piep,
        taping,
        hammering,
        hammering_once,
        bubble,
        bear_trap,
        explosion,
        short_gas_leak,
        alarm_short,
        water,
        drink,
        footstep_concrete1,
        footstep_concrete2,
        footstep_grass1,
        footstep_grass2,
        forest,
    }
}