using UnityEngine.Localization.SmartFormat.Core.Parsing;

public class ResourcesPath
{
    public static string[] PrefabPathArray =
    {
        "Prefabs/Test",
        "Prefabs/Survivor",
        "Prefabs/Bullet",
        "Prefabs/Rocket",
        "Prefabs/Arrow",
        "Prefabs/Beam",
        "Prefabs/Blood",
        "Prefabs/Traps/BearTrap",
        "Prefabs/Traps/LandMine",

        "Prefabs/Effects/Explosion",
        "Prefabs/Effects/GasLeak",

        // Map
        "Prefabs/Maps/2x2/Map_2x2_01",
        "Prefabs/Maps/2x2/Map_2x2_02",
        "Prefabs/Maps/2x2/Map_2x2_03",
        "Prefabs/Maps/2x2/Map_2x2_04",
        "Prefabs/Maps/2x2/Map_2x2_05",
        "Prefabs/Maps/2x2/Map_2x2_06",
        "Prefabs/Maps/2x2/Map_2x2_07",
        "Prefabs/Maps/2x2/Map_2x2_08",
        "Prefabs/Maps/2x2/Map_2x2_09",
        "Prefabs/Maps/2x2/Map_2x2_10",
        "Prefabs/Maps/2x2/Map_2x2_11",
        "Prefabs/Maps/2x2/Map_2x2_12",
        "Prefabs/Maps/3x3/Map_3x3_01",
        "Prefabs/Maps/3x3/Map_3x3_02",
        "Prefabs/Maps/3x3/Map_3x3_03",
        "Prefabs/Maps/3x3/Map_3x3_04",
        "Prefabs/Maps/3x3/Map_3x3_05",
        "Prefabs/Maps/3x3/Map_3x3_06",
        "Prefabs/Maps/4x4/Map_4x4_01",
        "Prefabs/Maps/4x4/Map_4x4_02",
        "Prefabs/Maps/4x4/Map_4x4_03",
        "Prefabs/Maps/5x5/Map_5x5_01",

        // UI
        "Prefabs/UIs/Alert",
        "Prefabs/UIs/SurvivorSchedule",
        "Prefabs/UIs/CraftableAllow",
        "Prefabs/UIs/ImageBox",
        "Prefabs/UIs/Characteristic",
        "Prefabs/UIs/Training",
        "Prefabs/UIs/Achievement",

        // In Game UI
        "Prefabs/UIs/KillLog",
        "Prefabs/UIs/Headshot",
    };

    public static string[] NavMeshDataPathArray =
    {
        "NavMeshDatas/Map_2x2_01",
        "NavMeshDatas/Map_2x2_02",
        "NavMeshDatas/Map_2x2_03",
        "NavMeshDatas/Map_2x2_04",
        "NavMeshDatas/Map_2x2_05",
        "NavMeshDatas/Map_2x2_06",
        "NavMeshDatas/Map_2x2_07",
        "NavMeshDatas/Map_2x2_08",
        "NavMeshDatas/Map_2x2_09",
        "NavMeshDatas/Map_2x2_10",
        "NavMeshDatas/Map_2x2_11",
        "NavMeshDatas/Map_2x2_12",
        "NavMeshDatas/Map_3x3_01",
        "NavMeshDatas/Map_3x3_02",
        "NavMeshDatas/Map_3x3_03",
        "NavMeshDatas/Map_3x3_04",
        "NavMeshDatas/Map_3x3_05",
        "NavMeshDatas/Map_3x3_06",
        "NavMeshDatas/Map_4x4_01",
        "NavMeshDatas/Map_4x4_02",
        "NavMeshDatas/Map_4x4_03",
        "NavMeshDatas/Map_5x5_01",
    };

    public static string[] SpritePathArray =
    {
        "Sprites/Unknown",
        "Sprites/Icons/Survivor",
        "Sprites/Icons/Box",
        "Sprites/Icons/Knife",
        "Sprites/Icons/Dagger",
        "Sprites/Icons/Bat",
        "Sprites/Icons/LongSword",
        "Sprites/Icons/Shovel",
        "Sprites/Icons/Revolver",
        "Sprites/Icons/Pistol",
        "Sprites/Icons/AssaultRifle",
        "Sprites/Icons/SubMachineGun",
        "Sprites/Icons/ShotGun",
        "Sprites/Icons/SniperRifle",
        "Sprites/Icons/Bazooka",
        "Sprites/Icons/LASER",
        "Sprites/Icons/Bow",
        "Sprites/Icons/AdvancedBow",
        "Sprites/Icons/Bullet_Revolver",
        "Sprites/Icons/Bullet_Pistol",
        "Sprites/Icons/Bullet_AssaultRifle",
        "Sprites/Icons/Bullet_SubMachineGun",
        "Sprites/Icons/Bullet_ShotGun",
        "Sprites/Icons/Bullet_SniperRifle",
        "Sprites/Icons/Rocket_Bazooka",
        "Sprites/Icons/Arrow",
        "Sprites/Icons/Arrow_Enchanted",
        "Sprites/Icons/LowLevelBulletproofHelmet",
        "Sprites/Icons/MiddleLevelBulletproofHelmet",
        "Sprites/Icons/HighLevelBulletproofHelmet",
        "Sprites/Icons/LegendaryBulletproofHelmet",
        "Sprites/Icons/LowLevelBulletproofVest",
        "Sprites/Icons/MiddleLevelBulletproofVest",
        "Sprites/Icons/HighLevelBulletproofVest",
        "Sprites/Icons/LegendaryBulletproofVest",
        "Sprites/Icons/BandageRoll",
        "Sprites/Icons/HemostaticBandageRoll",
        "Sprites/Icons/Poison",
        "Sprites/Icons/Antidote",
        "Sprites/Icons/Potion",
        "Sprites/Icons/AdvancedPotion",
        "Sprites/Icons/BearTrap",
        "Sprites/Icons/LandMine",
        "Sprites/Icons/NoiseTrap",
        "Sprites/Icons/ChemicalTrap",
        "Sprites/Icons/ShrapnelTrap",
        "Sprites/Icons/ExplosiveTrap",
        "Sprites/Icons/AdvancedComponent",
        "Sprites/Icons/Components",
        "Sprites/Icons/Chemicals",
        "Sprites/Icons/Salvages",
        "Sprites/Icons/Gunpowder",
        "Sprites/Icons/WalkingAid",
        "Sprites/Icons/TrapDetectionDevice",
        "Sprites/Icons/BiometricRader",
        "Sprites/Icons/EnergyBarrier",
        
        // Leagues
        "Sprites/Leagues/BronzeLeague",
        "Sprites/Leagues/SilverLeague",
        "Sprites/Leagues/GoldLeague",
        "Sprites/Leagues/SeasonChampionship",
        "Sprites/Leagues/WorldChampionship",
        "Sprites/Leagues/MeleeLeague",
        "Sprites/Leagues/RangeLeague",
        "Sprites/Leagues/CraftingLeague",
        "Sprites/Leagues/RegularLeague",

        "Sprites/Leagues/BronzeLeagueUntagged",
        "Sprites/Leagues/SilverLeagueUntagged",
        "Sprites/Leagues/GoldLeagueUntagged",
        "Sprites/Leagues/SeasonChampionshipUntagged",
        "Sprites/Leagues/WorldChampionshipUntagged",
        "Sprites/Leagues/MeleeLeagueUntagged",
        "Sprites/Leagues/RangeLeagueUntagged",
        "Sprites/Leagues/CraftingLeagueUntagged",

        "Sprites/Leagues/Localized/BronzeLeagueKR",
        "Sprites/Leagues/Localized/BronzeLeagueJP",
        "Sprites/Leagues/Localized/BronzeLeagueTC",
        "Sprites/Leagues/Localized/BronzeLeagueSC",
        "Sprites/Leagues/Localized/BronzeLeagueFR",
        "Sprites/Leagues/Localized/BronzeLeagueDE",
        "Sprites/Leagues/Localized/BronzeLeagueRU",
        "Sprites/Leagues/Localized/BronzeLeagueES",
        "Sprites/Leagues/Localized/BronzeLeaguePT",

        "Sprites/Leagues/Localized/SilverLeagueKR",
        "Sprites/Leagues/Localized/SilverLeagueJP",
        "Sprites/Leagues/Localized/SilverLeagueTC",
        "Sprites/Leagues/Localized/SilverLeagueSC",
        "Sprites/Leagues/Localized/SilverLeagueFR",
        "Sprites/Leagues/Localized/SilverLeagueDE",
        "Sprites/Leagues/Localized/SilverLeagueRU",
        "Sprites/Leagues/Localized/SilverLeagueES",
        "Sprites/Leagues/Localized/SilverLeaguePT",

        "Sprites/Leagues/Localized/GoldLeagueKR",
        "Sprites/Leagues/Localized/GoldLeagueJP",
        "Sprites/Leagues/Localized/GoldLeagueTC",
        "Sprites/Leagues/Localized/GoldLeagueSC",
        "Sprites/Leagues/Localized/GoldLeagueFR",
        "Sprites/Leagues/Localized/GoldLeagueDE",
        "Sprites/Leagues/Localized/GoldLeagueRU",
        "Sprites/Leagues/Localized/GoldLeagueES",
        "Sprites/Leagues/Localized/GoldLeaguePT",

        "Sprites/Leagues/Localized/SeasonChampionshipKR",
        "Sprites/Leagues/Localized/SeasonChampionshipJP",
        "Sprites/Leagues/Localized/SeasonChampionshipTC",
        "Sprites/Leagues/Localized/SeasonChampionshipSC",
        "Sprites/Leagues/Localized/SeasonChampionshipFR",
        "Sprites/Leagues/Localized/SeasonChampionshipDE",
        "Sprites/Leagues/Localized/SeasonChampionshipRU",
        "Sprites/Leagues/Localized/SeasonChampionshipES",
        "Sprites/Leagues/Localized/SeasonChampionshipPT",

        "Sprites/Leagues/Localized/WorldChampionshipKR",
        "Sprites/Leagues/Localized/WorldChampionshipJP",
        "Sprites/Leagues/Localized/WorldChampionshipTC",
        "Sprites/Leagues/Localized/WorldChampionshipSC",
        "Sprites/Leagues/Localized/WorldChampionshipFR",
        "Sprites/Leagues/Localized/WorldChampionshipDE",
        "Sprites/Leagues/Localized/WorldChampionshipRU",
        "Sprites/Leagues/Localized/WorldChampionshipES",
        "Sprites/Leagues/Localized/WorldChampionshipPT",

        "Sprites/Leagues/Localized/MeleeLeagueKR",
        "Sprites/Leagues/Localized/MeleeLeagueJP",
        "Sprites/Leagues/Localized/MeleeLeagueTC",
        "Sprites/Leagues/Localized/MeleeLeagueSC",
        "Sprites/Leagues/Localized/MeleeLeagueFR",
        "Sprites/Leagues/Localized/MeleeLeagueDE",
        "Sprites/Leagues/Localized/MeleeLeagueRU",
        "Sprites/Leagues/Localized/MeleeLeagueES",
        "Sprites/Leagues/Localized/MeleeLeaguePT",

        "Sprites/Leagues/Localized/RangeLeagueKR",
        "Sprites/Leagues/Localized/RangeLeagueJP",
        "Sprites/Leagues/Localized/RangeLeagueTC",
        "Sprites/Leagues/Localized/RangeLeagueSC",
        "Sprites/Leagues/Localized/RangeLeagueFR",
        "Sprites/Leagues/Localized/RangeLeagueDE",
        "Sprites/Leagues/Localized/RangeLeagueRU",
        "Sprites/Leagues/Localized/RangeLeagueES",
        "Sprites/Leagues/Localized/RangeLeaguePT",

        "Sprites/Leagues/Localized/CraftingLeagueKR",
        "Sprites/Leagues/Localized/CraftingLeagueJP",
        "Sprites/Leagues/Localized/CraftingLeagueTC",
        "Sprites/Leagues/Localized/CraftingLeagueSC",
        "Sprites/Leagues/Localized/CraftingLeagueFR",
        "Sprites/Leagues/Localized/CraftingLeagueDE",
        "Sprites/Leagues/Localized/CraftingLeagueRU",
        "Sprites/Leagues/Localized/CraftingLeagueES",
        "Sprites/Leagues/Localized/CraftingLeaguePT",

        "Sprites/Leagues/Localized/RegularLeagueKR",
        "Sprites/Leagues/Localized/RegularLeagueJP",
        "Sprites/Leagues/Localized/RegularLeagueTC",
        "Sprites/Leagues/Localized/RegularLeagueSC",
        "Sprites/Leagues/Localized/RegularLeagueFR",
        "Sprites/Leagues/Localized/RegularLeagueDE",
        "Sprites/Leagues/Localized/RegularLeagueRU",
        "Sprites/Leagues/Localized/RegularLeagueES",
        "Sprites/Leagues/Localized/RegularLeaguePT",

        // Tiers
        "Sprites/Leagues/Bronze",
        "Sprites/Leagues/Silver",
        "Sprites/Leagues/Gold",

        // Minimaps
        "Sprites/Minimaps/Minimap_2x2_01",
        "Sprites/Minimaps/Minimap_2x2_02",
        "Sprites/Minimaps/Minimap_2x2_03",
        "Sprites/Minimaps/Minimap_2x2_04",
        "Sprites/Minimaps/Minimap_2x2_05",
        "Sprites/Minimaps/Minimap_2x2_06",
        "Sprites/Minimaps/Minimap_2x2_07",
        "Sprites/Minimaps/Minimap_2x2_08",
        "Sprites/Minimaps/Minimap_2x2_09",
        "Sprites/Minimaps/Minimap_2x2_10",
        "Sprites/Minimaps/Minimap_2x2_11",
        "Sprites/Minimaps/Minimap_2x2_12",
        "Sprites/Minimaps/Minimap_3x3_01",
        "Sprites/Minimaps/Minimap_3x3_02",
        "Sprites/Minimaps/Minimap_3x3_03",
        "Sprites/Minimaps/Minimap_3x3_04",
        "Sprites/Minimaps/Minimap_3x3_05",
        "Sprites/Minimaps/Minimap_3x3_06",
        "Sprites/Minimaps/Minimap_4x4_01",
        "Sprites/Minimaps/Minimap_4x4_02",
        "Sprites/Minimaps/Minimap_4x4_03",
        "Sprites/Minimaps/Minimap_5x5_01",

        // Trainings
        "Sprites/Trainings/StrengthTraining",
        "Sprites/Trainings/Running",
        "Sprites/Trainings/AmmoCrateCarry",
        "Sprites/Trainings/LoadedRun",
        "Sprites/Trainings/TargetShooting",
        "Sprites/Trainings/CQCTraining",
        "Sprites/Trainings/CQBTraining",
        "Sprites/Trainings/Machining",
        "Sprites/Trainings/MechanicalDesign",
        "Sprites/Trainings/MilitaryLogisticsEngineering",
        "Sprites/Trainings/Engineering",
        "Sprites/Trainings/Judo",
        "Sprites/Trainings/SpecialOperationsTactics",
        "Sprites/Trainings/Boxing",
        "Sprites/Trainings/Wrestling",
        "Sprites/Trainings/MMATraining",
        "Sprites/Trainings/Taekwondo",
        "Sprites/Trainings/IndividualCombatTraining",
        "Sprites/Trainings/Powerlifting",
        "Sprites/Trainings/CombatEngineeringTraining",
        "Sprites/Trainings/RangerTraining",
        "Sprites/Trainings/ElectronicEngineering",
        "Sprites/Trainings/MMASparring",
        "Sprites/Trainings/BattleRoyaleSimulation",
        "Sprites/Trainings/TacticalShootingTraining",
        "Sprites/Trainings/EngineeringSociety",
        "Sprites/Trainings/InviteLocalExpert",
        "Sprites/Trainings/VisitHiddenMaster",
        "Sprites/Trainings/InviteStrongman",
        "Sprites/Trainings/InviteMMAChampion",
        "Sprites/Trainings/CraftingWorkshop",
        "Sprites/Trainings/InviteMeleeLeagueChampion",
        "Sprites/Trainings/InviteShootingLeagueChampion",
        "Sprites/Trainings/InviteCraftingLeagueChampion",
        "Sprites/Trainings/InviteSeasonChampion",
        "Sprites/Trainings/InviteWorldChampion",
        "Sprites/Trainings/VeteranBattleRoyalePlayerVisit",

        // Achievements
        "Sprites/Achievements/HundredThousandaire",
        "Sprites/Achievements/RoyalLoader",
        "Sprites/Achievements/BronzeCup",
        "Sprites/Achievements/SilverCup",
        "Sprites/Achievements/GoldCup",
        "Sprites/Achievements/SeasonChampion",
        "Sprites/Achievements/WorldChampion",
        "Sprites/Achievements/MeleeChampion",
        "Sprites/Achievements/ShootingChampion",
        "Sprites/Achievements/CraftingChampion",
        "Sprites/Achievements/BloodyHands",
        "Sprites/Achievements/BloodyArms",
        "Sprites/Achievements/Pentakill",
        "Sprites/Achievements/Notorious",
        "Sprites/Achievements/Tactician",
        "Sprites/Achievements/Legend",
        "Sprites/Achievements/VultureVictory",
        "Sprites/Achievements/Experience",
        "Sprites/Achievements/Powerhouse",
        "Sprites/Achievements/QuickFooted",
        "Sprites/Achievements/MartialArtist",
        "Sprites/Achievements/Sharpshooter",
        "Sprites/Achievements/Genius",
        "Sprites/Achievements/Foreman",
        "Sprites/Achievements/SunTzu",
        "Sprites/Achievements/_1hour",
        "Sprites/Achievements/Viper",
        "Sprites/Achievements/BruceLee",
        "Sprites/Achievements/LethalWeapon",
        "Sprites/Achievements/Gunslinger",
        "Sprites/Achievements/SwordMaster",
        "Sprites/Achievements/Sniper",
        "Sprites/Achievements/Ace",
        "Sprites/Achievements/SevereBleeding",
        "Sprites/Achievements/AugmentedProsthetic",
        "Sprites/Achievements/TranscendentProsthetic",
        "Sprites/Achievements/Masterpiece",
        "Sprites/Achievements/Overcome",
        "Sprites/Achievements/Craftsman",

        "Sprites/Achievements/HundredThousandaire_unlock",
        "Sprites/Achievements/RoyalLoader_unlock",
        "Sprites/Achievements/BronzeCup_unlock",
        "Sprites/Achievements/SilverCup_unlock",
        "Sprites/Achievements/GoldCup_unlock",
        "Sprites/Achievements/SeasonChampion_unlock",
        "Sprites/Achievements/WorldChampion_unlock",
        "Sprites/Achievements/MeleeChampion_unlock",
        "Sprites/Achievements/ShootingChampion_unlock",
        "Sprites/Achievements/CraftingChampion_unlock",
        "Sprites/Achievements/BloodyHands_unlock",
        "Sprites/Achievements/BloodyArms_unlock",
        "Sprites/Achievements/Pentakill_unlock",
        "Sprites/Achievements/Notorious_unlock",
        "Sprites/Achievements/Tactician_unlock",
        "Sprites/Achievements/Legend_unlock",
        "Sprites/Achievements/VultureVictory_unlock",
        "Sprites/Achievements/Experience_unlock",
        "Sprites/Achievements/Powerhouse_unlock",
        "Sprites/Achievements/QuickFooted_unlock",
        "Sprites/Achievements/MartialArtist_unlock",
        "Sprites/Achievements/Sharpshooter_unlock",
        "Sprites/Achievements/Genius_unlock",
        "Sprites/Achievements/Foreman_unlock",
        "Sprites/Achievements/SunTzu_unlock",
        "Sprites/Achievements/_1hour_unlock",
        "Sprites/Achievements/Viper_unlock",
        "Sprites/Achievements/BruceLee_unlock",
        "Sprites/Achievements/LethalWeapon_unlock",
        "Sprites/Achievements/Gunslinger_unlock",
        "Sprites/Achievements/SwordMaster_unlock",
        "Sprites/Achievements/Sniper_unlock",
        "Sprites/Achievements/Ace_unlock",
        "Sprites/Achievements/SevereBleeding_unlock",
        "Sprites/Achievements/AugmentedProsthetic_unlock",
        "Sprites/Achievements/TranscendentProsthetic_unlock",
        "Sprites/Achievements/Masterpiece_unlock",
        "Sprites/Achievements/Overcome_unlock",
        "Sprites/Achievements/Craftsman_unlock",
    };

    public static string[] MaterialPathArray =
    {
        "Materials/Sight/Sight_Normal",
        "Materials/Sight/Sight_Suspicious",
        "Materials/Sight/Sight_Alert",

    };

    public static string[] BGMPathArray =
    {
        "Sounds/BGMs/the_birth_of_hip_hop",

    };

    public static string[] SFXPathArray =
    {
        "Sounds/SFXs/Guns/assaultriflereload1",
        "Sounds/SFXs/Guns/Handgun_reload",
        "Sounds/SFXs/Guns/revolver_reload",
        "Sounds/SFXs/Guns/Shotgun_singlebullet",
        "Sounds/SFXs/Guns/Rack",
        "Sounds/SFXs/Guns/metal_hit",
        "Sounds/SFXs/Guns/bang_01",
        "Sounds/SFXs/Guns/bang_02",
        "Sounds/SFXs/Guns/bang_03",
        "Sounds/SFXs/Guns/bang_04",
        "Sounds/SFXs/Guns/bang_05",
        "Sounds/SFXs/Guns/bang_06",
        "Sounds/SFXs/Guns/rocket_launch",
        "Sounds/SFXs/Guns/laser",
        "Sounds/SFXs/Guns/ricochet",
        "Sounds/SFXs/Guns/ricochet2",
        "Sounds/SFXs/hit01",
        "Sounds/SFXs/hit02",
        "Sounds/SFXs/guard",
        "Sounds/SFXs/avoid",
        "Sounds/SFXs/farmingNoise01",
        "Sounds/SFXs/farmingNoise02",
        "Sounds/SFXs/farmingNoise03",
        "Sounds/SFXs/farmingNoise04",
        "Sounds/SFXs/piep",
        "Sounds/SFXs/taping",
        "Sounds/SFXs/hammering",
        "Sounds/SFXs/hammering_once",
        "Sounds/SFXs/bubble",
        "Sounds/SFXs/bear_trap",
        "Sounds/SFXs/explosion",
        "Sounds/SFXs/short_gas_leak",
        "Sounds/SFXs/alarm_short",
        "Sounds/SFXs/water",
        "Sounds/SFXs/drink",
        "Sounds/SFXs/footstep_concrete1",
        "Sounds/SFXs/footstep_concrete2",
        "Sounds/SFXs/footstep_grass1",
        "Sounds/SFXs/footstep_grass2",
        "Sounds/SFXs/forest",
        "Sounds/SFXs/bow_load",
        "Sounds/SFXs/bow_release",
        "Sounds/SFXs/bow_hit",
        "Sounds/SFXs/parrying",
    };

    public const string AudioMixerPath = "Sounds/AudioMixer";
}